# Generated by Django 6.0.4 on 2026-05-01 09:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('country', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('boycott_status', models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('review', 'Under review')], default='none', max_length=20)),
                ('boycott_reason', models.TextField(blank=True)),
                ('categories', models.CharField(blank=True, max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('aliases', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(choices=[('plant', 'Plant'), ('animal', 'Animal'), ('synthetic', 'Synthetic'), ('microbial', 'Microbial'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('possible_risks', models.TextField(blank=True)),
                ('typical_usage', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_type', models.CharField(choices=[('internal', 'Internal reference'), ('external', 'External source'), ('ai', 'AI analysis'), ('ocr', 'OCR import')], default='external', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('beverages', 'Beverages'), ('sweets', 'Sweets'), ('dairy', 'Dairy'), ('sauces', 'Sauces'), ('fast_food', 'Fast food'), ('cosmetics', 'Cosmetics'), ('medicine', 'Medicine'), ('supplements', 'Supplements'), ('semi_finished', 'Semi-finished'), ('meat', 'Meat'), ('baby', 'Baby products'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('full_ingredients_text', models.TextField(blank=True)),
                ('halal_status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_from_source_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('normalized_name', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_caches', to='catalog.product')),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='ocr/uploads/')),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('cleaned_ingredients_text', models.TextField(blank=True)),
                ('final_status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('final_reason', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_summary', models.TextField(blank=True)),
                ('source_name', models.CharField(default='user_upload', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_requests', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRIngredientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_hits', to='catalog.ingredient')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_results', to='catalog.productcheckrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('status_at_analysis', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_products', to='catalog.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('product', 'ingredient', 'position')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='catalog.ProductIngredient', to='catalog.ingredient'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_type', models.CharField(choices=[('product', 'Product'), ('ingredient', 'Ingredient'), ('brand', 'Brand'), ('ocr', 'OCR')], max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('result_status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('doubtful', 'Doubtful'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='catalog.brand')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='catalog.ingredient')),
                ('ocr_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='catalog.productcheckrequest')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('alternative_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for', to='catalog.product')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='catalog.product')),
            ],
            options={
                'unique_together': {('source_product', 'alternative_product')},
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_product_per_brand'),
        ),
    ]
