# Generated by Django 6.0.4 on 2026-05-01 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externalproductcache',
            index=models.Index(fields=['query', 'provider'], name='catalog_ext_query_84d23e_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproductcache',
            index=models.Index(fields=['last_synced_at'], name='catalog_ext_last_sy_ecefbf_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-created_at'], name='catalog_sea_user_id_63b203_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['check_type', 'query'], name='catalog_sea_check_t_fccf6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('ingredient__isnull', True), ('brand__isnull', True)), models.Q(('product__isnull', True), ('ingredient__isnull', False), ('brand__isnull', True)), models.Q(('product__isnull', True), ('ingredient__isnull', True), ('brand__isnull', False)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_favorite_product_per_user'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('ingredient__isnull', False)), fields=('user', 'ingredient'), name='unique_favorite_ingredient_per_user'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('user', 'brand'), name='unique_favorite_brand_per_user'),
        ),
    ]
